[project]
name = "lauv-sdk"
version = "0.0.1"
description = "Lauv CDN SDK for Python"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
